version: '2'

services:


  mysql-db:
    image: mysql:latest
    container_name: mysql-db
    networks: 
      - arm-mreza
    environment: 
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=wt22
      
      
      
  nodejs-app:
    image: hbisevac1/arm-zadaca:nodejs-app
    container_name: nodejs-app
    ports:
      - "3000:3000"
    networks:
      - arm-mreza
    depends_on: 
      - mysql-db
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 35
         
networks: 
  arm-mreza:
    name: arm-mreza
    driver: bridge
    
    
    
    
    
    
    
    
    
    
    
    
    
    
